name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make re

  build_macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make re
